version: '3'
volumes:
  db-data:


services:
  web:
    build: .
    ports:
    - '3000:3000'
    volumes:
    - '.:/rails-docker-mysql'
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    image: mysql:8
    volumes:
    - 'db-data:/var/lib/mysql'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password